import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = path.resolve(__dirname, '..');
const repoRoot = path.resolve(projectRoot, '..', '..');
const capstoneRoot = path.resolve(repoRoot, '..');

const model = process.env.OPENROUTER_MODEL || 'google/gemini-3.1-flash-lite';
const criticModel = process.env.OPENROUTER_CRITIC_MODEL || model;
const endpoint = 'https://openrouter.ai/api/v1/chat/completions';

const skillIds = [
  'addition-by-subtraction',
  'blindside',
  'breakout',
  'breakthrough',
  'constraint-injection',
  'first-principles',
  'polymath',
];

const tones = {
  'addition-by-subtraction': 'mint',
  blindside: 'pink',
  breakout: 'violet',
  breakthrough: 'gold',
  'constraint-injection': 'blue',
  'first-principles': 'cyan',
  polymath: 'green',
};

const phenotypeDirectives = {
  'addition-by-subtraction':
    'Your answer must improve the situation by removing a tempting response, dependency, step, or assumption. Prefer quiet non-engagement and operational deletion over new equipment.',
  blindside:
    'Your answer must center the non-obvious failure mode: what the paparazzi, crew, owner, or protocol might exploit or misunderstand. Include the hardening move.',
  breakout:
    'Your answer must leave the anti-drone frame. Do not merely add a countermeasure; change the scene, incentive, environment, or definition of success.',
  breakthrough:
    'Your answer must name the single best accretive addition that makes the solution click. It should feel obvious-in-retrospect and practical.',
  'constraint-injection':
    'Your answer must derive from a deliberately harsh constraint: no RF, no takedown, no visible panic, no complex deliberation, and a short execution window.',
  'first-principles':
    'Your answer must derive from irreducible truths. Separate the real protected asset from inherited anti-drone assumptions before proposing action.',
  polymath:
    'Your answer must transplant a proven mechanism from a distant field and map it concretely onto yacht operations.',
};

const scoreNames = ['grounding', 'novelty', 'feasibility', 'falsification', 'operationalFit'];

async function main() {
  const apiKey = await getOpenRouterKey();
  const caseText = await readFile(
    path.join(repoRoot, 'scratchpad/case-studies/jack-drone-privacy-withheld-solution.md'),
    'utf8',
  );
  const skills = await loadSkills();
  const parentResults = [];

  for (const skill of skills) {
    log(`Generating parent: ${skill.id}`);
    const proposal = await generateParent(apiKey, caseText, skill);
    log(`Critiquing parent: ${skill.id}`);
    const critique = await critiqueArtifact(apiKey, caseText, {
      title: proposal.title,
      proposal: proposal.proposal,
      validationPlan: proposal.validationPlan,
      producer: skill.id,
      artifactKind: 'parent',
    });
    parentResults.push(parentResult(skill, proposal, critique));
  }

  const runs = {};
  for (let i = 0; i < parentResults.length; i += 1) {
    for (let j = i + 1; j < parentResults.length; j += 1) {
      const left = parentResults[i];
      const right = parentResults[j];
      const key = pairKey(left.id, right.id);
      log(`Generating child: ${key}`);
      const childProposal = await generateChild(apiKey, caseText, left, right);
      log(`Critiquing child: ${key}`);
      const childCritique = await critiqueArtifact(apiKey, caseText, {
        title: childProposal.title,
        proposal: childProposal.proposal,
        validationPlan: childProposal.validationPlan,
        producer: `${left.id} x ${right.id}`,
        artifactKind: 'child',
      });
      runs[key] = runResult(left, right, childProposal, childCritique);
    }
  }

  const output = {
    schemaVersion: 1,
    generatedAt: new Date().toISOString(),
    caseId: 'jack-superyacht-drone-privacy-withheld-solution',
    caseTitle: 'Jack Superyacht Drone Privacy',
    generationModel: model,
    criticModel,
    method:
      'Generated by scripts/generateFusionRuns.js. Parent proposals, parent critic panels, child proposals, and child critic panels were separate OpenRouter calls against the withheld-solution case.',
    scoreNames,
    agenomes: Object.fromEntries(parentResults.map((parent) => [parent.id, parent])),
    runs,
  };

  await writeFile(
    path.join(projectRoot, 'src/fusionRuns.generated.json'),
    `${JSON.stringify(output, null, 2)}\n`,
  );
  log(`Wrote ${Object.keys(runs).length} fusion runs for ${parentResults.length} agenomes.`);
}

async function loadSkills() {
  const skills = [];
  for (const id of skillIds) {
    const text = await readFile(path.join(repoRoot, `.cursor/skills/${id}/SKILL.md`), 'utf8');
    const title = id
      .split('-')
      .map((part) => part[0].toUpperCase() + part.slice(1))
      .join(' ');
    skills.push({
      id,
      label: id,
      title,
      tone: tones[id],
      text: text.slice(0, 6000),
    });
  }
  return skills;
}

async function generateParent(apiKey, caseText, skill) {
  return callJson(apiKey, model, [
    {
      role: 'system',
      content:
        'You are running one Doppl agenome against a withheld-solution case. Produce a concise, concrete solution artifact. Return JSON only.',
    },
    {
      role: 'user',
      content: `CASE STUDY WITHOUT SOLUTION:\n${caseText}\n\nAGENOME SKILL:\n${skill.text}\n\nPHENOTYPE REQUIREMENT:\n${phenotypeDirectives[skill.id]}\n\nAct only as the ${skill.id} agenome. Do not mention that the known solution is withheld. Generate the best solution this specific agenome would propose. Make the proposal visibly different from what a generic anti-drone consultant would say.\n\nReturn JSON with keys: title, proposal, whyThisFits, tradeoffs, validationPlan, inheritedTrait. Keep proposal under 90 words. Keep other string fields under 45 words.`,
    },
  ]);
}

async function generateChild(apiKey, caseText, left, right) {
  const leftAvg = average(left.scores);
  const rightAvg = average(right.scores);
  const total = leftAvg + rightAvg;
  const leftShare = Math.round((leftAvg / total) * 100);
  const rightShare = 100 - leftShare;

  return callJson(apiKey, model, [
    {
      role: 'system',
      content:
        'You are running Doppl reproduction. Breed a child agenome from two scored parent artifacts. Produce the child artifact, not commentary. Return JSON only.',
    },
    {
      role: 'user',
      content: `CASE STUDY WITHOUT SOLUTION:\n${caseText}\n\nPARENT A (${left.id}) score avg ${leftAvg}, inheritance share ${leftShare}%:\n${JSON.stringify(parentForPrompt(left), null, 2)}\n\nPARENT B (${right.id}) score avg ${rightAvg}, inheritance share ${rightShare}%:\n${JSON.stringify(parentForPrompt(right), null, 2)}\n\nBreed a child that uses the stronger parent's best traits more heavily while preserving the other parent's strongest blind-spot coverage. The child should be a concrete yacht operating solution.\n\nReturn JSON with keys: title, proposal, fusionLogic, inheritedTraits (array of 3 short strings), tradeoffs, validationPlan. Keep proposal under 95 words.`,
    },
  ]);
}

async function critiqueArtifact(apiKey, caseText, artifact) {
  const result = await callJson(apiKey, criticModel, [
    {
      role: 'system',
      content:
        'You are a held-out adversarial critic council for a Doppl prototype. Score strictly but fairly. Return JSON only.',
    },
    {
      role: 'user',
      content: `CASE STUDY WITHOUT SOLUTION:\n${caseText}\n\nARTIFACT TO SCORE:\n${JSON.stringify(artifact, null, 2)}\n\nScore from 0 to 100 on: grounding, novelty, feasibility, falsification, operationalFit.\n- grounding: uses only plausible facts and case context\n- novelty: avoids generic anti-drone advice\n- feasibility: can work with realistic yacht operations\n- falsification: names real failure modes / is testable\n- operationalFit: fits discretion, legality, safety, and crew simplicity\n\nReturn JSON with keys: scores (object with exactly those numeric fields), verdict, strongestCritic, hardestPressure. Keep verdict under 35 words.`,
    },
  ]);
  return normalizeCritique(result);
}

async function callJson(apiKey, selectedModel, messages) {
  let lastError;
  for (let attempt = 1; attempt <= 3; attempt += 1) {
    try {
      const response = await fetch(endpoint, {
        method: 'POST',
        headers: {
          Authorization: `Bearer ${apiKey}`,
          'Content-Type': 'application/json',
          'HTTP-Referer': 'https://doppl-life.github.io/mh-doppl-spike/',
          'X-Title': 'Doppl fusion prototype generator',
        },
        body: JSON.stringify({
          model: selectedModel,
          messages: attempt === 1
            ? messages
            : [
                ...messages,
                {
                  role: 'user',
                  content:
                    'Your previous response was invalid or truncated. Return one complete valid JSON object only. No markdown, no prose outside JSON.',
                },
              ],
          temperature: 0.35,
          max_tokens: 1100,
          response_format: { type: 'json_object' },
        }),
      });

      if (!response.ok) {
        const text = await response.text();
        throw new Error(`OpenRouter ${response.status}: ${text.slice(0, 500)}`);
      }

      const data = await response.json();
      const content = data.choices?.[0]?.message?.content;
      if (!content) throw new Error('OpenRouter returned no message content.');
      return parseJson(content);
    } catch (error) {
      lastError = error;
      log(`JSON call failed on attempt ${attempt}: ${error.message}`);
    }
  }
  throw lastError;
}

function parseJson(content) {
  try {
    return JSON.parse(content);
  } catch {
    const match = content.match(/\{[\s\S]*\}/);
    if (!match) throw new Error(`Could not parse JSON: ${content.slice(0, 240)}`);
    return JSON.parse(match[0]);
  }
}

function parentResult(skill, proposal, critique) {
  return {
    id: skill.id,
    label: skill.label,
    title: skill.title,
    tone: skill.tone,
    move: proposal.inheritedTrait || proposal.whyThisFits || skill.title,
    proposal: proposal.proposal,
    whyThisFits: proposal.whyThisFits,
    tradeoffs: proposal.tradeoffs,
    validationPlan: proposal.validationPlan,
    scores: critique.scores,
    verdict: critique.verdict,
    strongestCritic: critique.strongestCritic,
    hardestPressure: critique.hardestPressure,
    trait: proposal.inheritedTrait || skill.title,
  };
}

function runResult(left, right, childProposal, childCritique) {
  const leftAverage = average(left.scores);
  const rightAverage = average(right.scores);
  const total = leftAverage + rightAverage;
  const leftShare = Math.round((leftAverage / total) * 100);
  const rightShare = 100 - leftShare;
  return {
    ids: [left.id, right.id],
    parentA: parentRunSide(left),
    parentB: parentRunSide(right),
    fusionRatio: `${leftShare}:${rightShare}`,
    inheritanceLogic:
      childProposal.fusionLogic ||
      `${left.title} contributes ${leftShare}% and ${right.title} contributes ${rightShare}% based on critic scores.`,
    child: {
      title: childProposal.title,
      proposal: childProposal.proposal,
      tradeoffs: childProposal.tradeoffs,
      validationPlan: childProposal.validationPlan,
      scores: childCritique.scores,
      verdict: childCritique.verdict,
      strongestCritic: childCritique.strongestCritic,
      hardestPressure: childCritique.hardestPressure,
      inheritedTraits: normalizeTraits(childProposal.inheritedTraits, left, right),
    },
  };
}

function parentRunSide(parent) {
  return {
    agenome: parent.label,
    title: parent.title,
    proposal: parent.proposal,
    scores: parent.scores,
    verdict: parent.verdict,
    strongestCritic: parent.strongestCritic,
    hardestPressure: parent.hardestPressure,
  };
}

function parentForPrompt(parent) {
  return {
    agenome: parent.label,
    proposal: parent.proposal,
    scores: parent.scores,
    verdict: parent.verdict,
    strongestCritic: parent.strongestCritic,
    hardestPressure: parent.hardestPressure,
  };
}

function normalizeCritique(result) {
  const rawScores = result.scores || {};
  const scores = Object.fromEntries(scoreNames.map((name) => {
    const value = Number(rawScores[name]);
    return [name, Number.isFinite(value) ? Math.max(0, Math.min(100, Math.round(value))) : 50];
  }));
  return {
    scores,
    verdict: String(result.verdict || 'Critic panel returned no verdict.'),
    strongestCritic: String(result.strongestCritic || 'Unspecified strongest critic signal.'),
    hardestPressure: String(result.hardestPressure || 'Unspecified remaining pressure.'),
  };
}

function normalizeTraits(traits, left, right) {
  if (Array.isArray(traits) && traits.length > 0) {
    return traits.slice(0, 4).map((trait) => String(trait));
  }
  return [left.trait, right.trait, 'critic pressure converted into a testable child'];
}

function average(scores) {
  const values = Object.values(scores).map(Number).filter(Number.isFinite);
  return Math.round(values.reduce((sum, value) => sum + value, 0) / values.length);
}

function pairKey(firstId, secondId) {
  return [firstId, secondId].sort().join('__');
}

async function getOpenRouterKey() {
  if (process.env.OPENROUTER_API_KEY) return process.env.OPENROUTER_API_KEY.trim();
  const keyFile = path.join(capstoneRoot, 'tokens and keys.md');
  const text = await readFile(keyFile, 'utf8');
  const match = text.match(/sk-or-v1-[A-Za-z0-9_-]+/);
  if (!match) {
    throw new Error('OPENROUTER_API_KEY not set and no OpenRouter key found in tokens and keys.md');
  }
  return match[0];
}

function log(message) {
  process.stderr.write(`${message}\n`);
}

main().catch((error) => {
  console.error(error.message);
  process.exit(1);
});
