import { appendFile, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = path.resolve(__dirname, '..');
const repoRoot = path.resolve(projectRoot, '..', '..');
const generationRunLedgerPath = path.join(repoRoot, 'agora/ledger/generation_runs.jsonl');

const model = process.env.OPENROUTER_MODEL || 'google/gemini-3.1-flash-lite';
const criticModel = process.env.OPENROUTER_CRITIC_MODEL || model;
const endpoint = 'https://openrouter.ai/api/v1/chat/completions';
let costEventSequence = 0;

const skillIds = [
  'addition-by-subtraction',
  'blindside',
  'breakout',
  'breakthrough',
  'constraint-injection',
  'first-principles',
  'polymath',
];

const tones = {
  'addition-by-subtraction': 'mint',
  blindside: 'pink',
  breakout: 'violet',
  breakthrough: 'gold',
  'constraint-injection': 'blue',
  'first-principles': 'cyan',
  polymath: 'green',
};

const phenotypeDirectives = {
  'addition-by-subtraction':
    'Your answer must improve the situation by removing a tempting response, dependency, step, or assumption. Prefer quiet non-engagement and operational deletion over new equipment.',
  blindside:
    'Your answer must center the non-obvious failure mode: what the paparazzi, crew, owner, or protocol might exploit or misunderstand. Include the hardening move.',
  breakout:
    'Your answer must leave the anti-drone frame. Do not merely add a countermeasure; change the scene, incentive, environment, or definition of success.',
  breakthrough:
    'Your answer must name the single best accretive addition that makes the solution click. It should feel obvious-in-retrospect and practical.',
  'constraint-injection':
    'Your answer must derive from a deliberately harsh constraint: no RF, no takedown, no visible panic, no complex deliberation, and a short execution window.',
  'first-principles':
    'Your answer must derive from irreducible truths. Separate the real protected asset from inherited anti-drone assumptions before proposing action.',
  polymath:
    'Your answer must transplant a proven mechanism from a distant field and map it concretely onto yacht operations.',
};

const scoreNames = ['grounding', 'novelty', 'feasibility', 'falsification', 'operationalFit'];

async function main() {
  const apiKey = getOpenRouterKey();
  const startedAt = new Date().toISOString();
  const costEvents = [];
  const caseText = await readFile(
    path.join(repoRoot, 'scratchpad/case-studies/jack-drone-privacy-withheld-solution.md'),
    'utf8',
  );
  const skills = await loadSkills();
  const parentResults = [];

  for (const skill of skills) {
    log(`Generating parent: ${skill.id}`);
    const proposal = await generateParent(apiKey, caseText, skill, costEvents);
    log(`Critiquing parent: ${skill.id}`);
    const critique = await critiqueArtifact(apiKey, caseText, {
      title: proposal.title,
      proposal: proposal.proposal,
      validationPlan: proposal.validationPlan,
      producer: skill.id,
      artifactKind: 'parent',
    }, {
      costEvents,
      outputId: `parent:${skill.id}`,
      stage: 'parent_critique',
      strategyLabels: [skill.id],
    });
    parentResults.push(parentResult(skill, proposal, critique));
  }

  const runs = {};
  for (let i = 0; i < parentResults.length; i += 1) {
    for (let j = i + 1; j < parentResults.length; j += 1) {
      const left = parentResults[i];
      const right = parentResults[j];
      const key = pairKey(left.id, right.id);
      log(`Generating child: ${key}`);
      const childProposal = await generateChild(apiKey, caseText, left, right, key, costEvents);
      log(`Critiquing child: ${key}`);
      const childCritique = await critiqueArtifact(apiKey, caseText, {
        title: childProposal.title,
        proposal: childProposal.proposal,
        validationPlan: childProposal.validationPlan,
        producer: `${left.id} x ${right.id}`,
        artifactKind: 'child',
      }, {
        costEvents,
        outputId: `child:${key}`,
        stage: 'child_critique',
        strategyLabels: [left.id, right.id],
      });
      runs[key] = runResult(left, right, childProposal, childCritique);
    }
  }

  const endedAt = new Date().toISOString();
  const generationRun = buildGenerationRun({
    startedAt,
    endedAt,
    costEvents,
    parentResults,
    runs,
  });

  const output = {
    schemaVersion: 1,
    generatedAt: new Date().toISOString(),
    caseId: 'jack-superyacht-drone-privacy-withheld-solution',
    caseTitle: 'Jack Superyacht Drone Privacy',
    generationModel: model,
    criticModel,
    method:
      'Generated by scripts/generateFusionRuns.js. Parent proposals, parent critic panels, child proposals, and child critic panels were separate OpenRouter calls against the withheld-solution case.',
    scoreNames,
    generationRun,
    agenomes: Object.fromEntries(parentResults.map((parent) => [parent.id, parent])),
    runs,
  };

  await writeFile(
    path.join(projectRoot, 'src/fusionRuns.generated.json'),
    `${JSON.stringify(output, null, 2)}\n`,
  );
  await appendFile(generationRunLedgerPath, `${JSON.stringify(generationRun)}\n`);
  log(
    `Wrote ${Object.keys(runs).length} fusion runs for ${parentResults.length} agenomes; ` +
    `${costEvents.length} cost events, total ${formatMoney(generationRun.total_cost_usd)}.`,
  );
}

async function loadSkills() {
  const skills = [];
  for (const id of skillIds) {
    const text = await readFile(path.join(repoRoot, `.cursor/skills/${id}/SKILL.md`), 'utf8');
    const title = id
      .split('-')
      .map((part) => part[0].toUpperCase() + part.slice(1))
      .join(' ');
    skills.push({
      id,
      label: id,
      title,
      tone: tones[id],
      text: text.slice(0, 6000),
    });
  }
  return skills;
}

async function generateParent(apiKey, caseText, skill, costEvents) {
  return callJson(apiKey, model, [
    {
      role: 'system',
      content:
        'You are running one Doppl agenome against a withheld-solution case. Produce a concise, concrete solution artifact. Return JSON only.',
    },
    {
      role: 'user',
      content: `CASE STUDY WITHOUT SOLUTION:\n${caseText}\n\nAGENOME SKILL:\n${skill.text}\n\nPHENOTYPE REQUIREMENT:\n${phenotypeDirectives[skill.id]}\n\nAct only as the ${skill.id} agenome. Do not mention that the known solution is withheld. Generate the best solution this specific agenome would propose. Make the proposal visibly different from what a generic anti-drone consultant would say.\n\nReturn JSON with keys: title, proposal, whyThisFits, tradeoffs, validationPlan, inheritedTrait. Keep proposal under 90 words. Keep other string fields under 45 words.`,
    },
  ], {
    costEvents,
    outputId: `parent:${skill.id}`,
    stage: 'parent_generation',
    strategyLabels: [skill.id],
  });
}

async function generateChild(apiKey, caseText, left, right, key, costEvents) {
  const leftAvg = average(left.scores);
  const rightAvg = average(right.scores);
  const total = leftAvg + rightAvg;
  const leftShare = Math.round((leftAvg / total) * 100);
  const rightShare = 100 - leftShare;

  return callJson(apiKey, model, [
    {
      role: 'system',
      content:
        'You are running Doppl reproduction. Breed a child agenome from two scored parent artifacts. Produce the child artifact, not commentary. Return JSON only.',
    },
    {
      role: 'user',
      content: `CASE STUDY WITHOUT SOLUTION:\n${caseText}\n\nPARENT A (${left.id}) score avg ${leftAvg}, inheritance share ${leftShare}%:\n${JSON.stringify(parentForPrompt(left), null, 2)}\n\nPARENT B (${right.id}) score avg ${rightAvg}, inheritance share ${rightShare}%:\n${JSON.stringify(parentForPrompt(right), null, 2)}\n\nBreed a child that uses the stronger parent's best traits more heavily while preserving the other parent's strongest blind-spot coverage. The child should be a concrete yacht operating solution.\n\nReturn JSON with keys: title, proposal, fusionLogic, inheritedTraits (array of 3 short strings), tradeoffs, validationPlan. Keep proposal under 95 words.`,
    },
  ], {
    costEvents,
    outputId: `child:${key}`,
    stage: 'child_generation',
    strategyLabels: [left.id, right.id],
  });
}

async function critiqueArtifact(apiKey, caseText, artifact, costContext) {
  const result = await callJson(apiKey, criticModel, [
    {
      role: 'system',
      content:
        'You are a held-out adversarial critic council for a Doppl prototype. Score strictly but fairly. Return JSON only.',
    },
    {
      role: 'user',
      content: `CASE STUDY WITHOUT SOLUTION:\n${caseText}\n\nARTIFACT TO SCORE:\n${JSON.stringify(artifact, null, 2)}\n\nScore from 0 to 100 on: grounding, novelty, feasibility, falsification, operationalFit.\n- grounding: uses only plausible facts and case context\n- novelty: avoids generic anti-drone advice\n- feasibility: can work with realistic yacht operations\n- falsification: names real failure modes / is testable\n- operationalFit: fits discretion, legality, safety, and crew simplicity\n\nReturn JSON with keys: scores (object with exactly those numeric fields), verdict, strongestCritic, hardestPressure. Keep verdict under 35 words.`,
    },
  ], costContext);
  return normalizeCritique(result);
}

async function callJson(apiKey, selectedModel, messages, costContext = {}) {
  let lastError;
  for (let attempt = 1; attempt <= 3; attempt += 1) {
    try {
      const response = await fetch(endpoint, {
        method: 'POST',
        headers: {
          Authorization: `Bearer ${apiKey}`,
          'Content-Type': 'application/json',
          'HTTP-Referer': 'https://doppl-life.github.io/mh-doppl-spike/',
          'X-Title': 'Doppl fusion prototype generator',
        },
        body: JSON.stringify({
          model: selectedModel,
          messages: attempt === 1
            ? messages
            : [
                ...messages,
                {
                  role: 'user',
                  content:
                    'Your previous response was invalid or truncated. Return one complete valid JSON object only. No markdown, no prose outside JSON.',
                },
              ],
          temperature: 0.35,
          max_tokens: 1100,
          response_format: { type: 'json_object' },
        }),
      });

      if (!response.ok) {
        const text = await response.text();
        throw new Error(`OpenRouter ${response.status}: ${text.slice(0, 500)}`);
      }

      const data = await response.json();
      recordCostEvent(costContext, data, selectedModel, attempt);
      const content = data.choices?.[0]?.message?.content;
      if (!content) throw new Error('OpenRouter returned no message content.');
      return parseJson(content);
    } catch (error) {
      lastError = error;
      log(`JSON call failed on attempt ${attempt}: ${error.message}`);
    }
  }
  throw lastError;
}

function parseJson(content) {
  try {
    return JSON.parse(content);
  } catch {
    const match = content.match(/\{[\s\S]*\}/);
    if (!match) throw new Error(`Could not parse JSON: ${content.slice(0, 240)}`);
    return JSON.parse(match[0]);
  }
}

function parentResult(skill, proposal, critique) {
  return {
    id: skill.id,
    label: skill.label,
    title: skill.title,
    tone: skill.tone,
    move: proposal.inheritedTrait || proposal.whyThisFits || skill.title,
    proposal: proposal.proposal,
    whyThisFits: proposal.whyThisFits,
    tradeoffs: proposal.tradeoffs,
    validationPlan: proposal.validationPlan,
    scores: critique.scores,
    verdict: critique.verdict,
    strongestCritic: critique.strongestCritic,
    hardestPressure: critique.hardestPressure,
    trait: proposal.inheritedTrait || skill.title,
  };
}

function runResult(left, right, childProposal, childCritique) {
  const leftAverage = average(left.scores);
  const rightAverage = average(right.scores);
  const total = leftAverage + rightAverage;
  const leftShare = Math.round((leftAverage / total) * 100);
  const rightShare = 100 - leftShare;
  return {
    ids: [left.id, right.id],
    parentA: parentRunSide(left),
    parentB: parentRunSide(right),
    fusionRatio: `${leftShare}:${rightShare}`,
    inheritanceLogic:
      childProposal.fusionLogic ||
      `${left.title} contributes ${leftShare}% and ${right.title} contributes ${rightShare}% based on critic scores.`,
    child: {
      title: childProposal.title,
      proposal: childProposal.proposal,
      tradeoffs: childProposal.tradeoffs,
      validationPlan: childProposal.validationPlan,
      scores: childCritique.scores,
      verdict: childCritique.verdict,
      strongestCritic: childCritique.strongestCritic,
      hardestPressure: childCritique.hardestPressure,
      inheritedTraits: normalizeTraits(childProposal.inheritedTraits, left, right),
    },
  };
}

function parentRunSide(parent) {
  return {
    agenome: parent.label,
    title: parent.title,
    proposal: parent.proposal,
    scores: parent.scores,
    verdict: parent.verdict,
    strongestCritic: parent.strongestCritic,
    hardestPressure: parent.hardestPressure,
  };
}

function parentForPrompt(parent) {
  return {
    agenome: parent.label,
    proposal: parent.proposal,
    scores: parent.scores,
    verdict: parent.verdict,
    strongestCritic: parent.strongestCritic,
    hardestPressure: parent.hardestPressure,
  };
}

function normalizeCritique(result) {
  const rawScores = result.scores || {};
  const scores = Object.fromEntries(scoreNames.map((name) => {
    const value = Number(rawScores[name]);
    return [name, Number.isFinite(value) ? Math.max(0, Math.min(100, Math.round(value))) : 50];
  }));
  return {
    scores,
    verdict: String(result.verdict || 'Critic panel returned no verdict.'),
    strongestCritic: String(result.strongestCritic || 'Unspecified strongest critic signal.'),
    hardestPressure: String(result.hardestPressure || 'Unspecified remaining pressure.'),
  };
}

function normalizeTraits(traits, left, right) {
  if (Array.isArray(traits) && traits.length > 0) {
    return traits.slice(0, 4).map((trait) => String(trait));
  }
  return [left.trait, right.trait, 'critic pressure converted into a testable child'];
}

function buildGenerationRun({ startedAt, endedAt, costEvents, parentResults, runs }) {
  const childOutputs = Object.entries(runs).map(([key, run]) => {
    const qualityScore = average(run.child.scores);
    const spaceOpeningScore = spaceOpening(run.child.scores);
    return {
      output_id: `child:${key}`,
      kind: 'fruit',
      title: run.child.title,
      selected: qualityScore >= 90,
      strategy_labels: [...run.ids],
      quality_score: qualityScore,
      space_opening_score: spaceOpeningScore,
    };
  });

  const parentOutputs = parentResults.map((parent) => ({
    output_id: `parent:${parent.id}`,
    kind: 'sprout',
    title: parent.title,
    selected: false,
    strategy_labels: [parent.id],
    quality_score: average(parent.scores),
    space_opening_score: spaceOpening(parent.scores),
  }));

  const totalCost = sumExactCosts(costEvents);
  return {
    run_id: `fusion-${startedAt.replace(/[:.]/g, '-')}`,
    objective: 'Breed mutagen agenomes against the Jack superyacht drone privacy withheld-solution case.',
    started_at: startedAt,
    ended_at: endedAt,
    arcade_id: 'fusion-lab',
    graph_node_ids: [...skillIds, ...Object.keys(runs)],
    strategy_labels: [...skillIds],
    currency: 'USD',
    total_cost_usd: totalCost,
    total_cost_exact: costEvents.length > 0 && costEvents.every((event) => event.exact),
    cost_events: costEvents,
    outputs: [...parentOutputs, ...childOutputs],
    judgments: childOutputs.map((output) => {
      const run = runs[output.output_id.replace('child:', '')];
      const scores = run.child.scores;
      return {
        rubric_version: 'space-opening.v0',
        output_id: output.output_id,
        novelty: scores.novelty,
        usefulness: scores.operationalFit,
        generality: output.space_opening_score,
        elegance: scores.feasibility,
        evidence: scores.grounding,
        surprise: scores.falsification,
        notes: run.child.verdict,
      };
    }),
    notes:
      'OpenRouter usage.cost is captured from each non-streaming response. Historical generated fixtures before this field are unmetered.',
  };
}

function recordCostEvent(context, data, selectedModel, attempt) {
  if (!context.costEvents) return;
  const usage = data.usage || {};
  const totalCost = moneyNumber(usage.cost);
  context.costEvents.push({
    event_id: `cost-${String(++costEventSequence).padStart(4, '0')}`,
    provider: 'openrouter',
    model_or_tool: data.model || selectedModel,
    stage: context.stage || 'chat_completion',
    units: {
      prompt_tokens: numberOrNull(usage.prompt_tokens),
      completion_tokens: numberOrNull(usage.completion_tokens),
      total_tokens: numberOrNull(usage.total_tokens),
      cached_tokens: numberOrNull(usage.prompt_tokens_details?.cached_tokens),
      reasoning_tokens: numberOrNull(usage.completion_tokens_details?.reasoning_tokens),
      attempt,
    },
    total_cost_usd: totalCost,
    exact: totalCost !== null,
    source: totalCost === null ? 'openrouter.response.usage.missing_cost' : 'openrouter.response.usage.cost',
    provider_request_id: data.id || '',
    strategy_labels: context.strategyLabels || [],
    output_id: context.outputId || '',
    ts: new Date().toISOString(),
  });
}

function spaceOpening(scores) {
  return Math.round(
    (Number(scores.novelty) || 0) * 0.35 +
    (Number(scores.falsification) || 0) * 0.25 +
    (Number(scores.operationalFit) || 0) * 0.2 +
    (Number(scores.grounding) || 0) * 0.1 +
    (Number(scores.feasibility) || 0) * 0.1,
  );
}

function sumExactCosts(costEvents) {
  if (costEvents.length === 0) return null;
  const values = costEvents.map((event) => event.total_cost_usd);
  if (values.some((value) => typeof value !== 'number' || !Number.isFinite(value))) return null;
  return Number(values.reduce((sum, value) => sum + value, 0).toFixed(8));
}

function moneyNumber(value) {
  const number = Number(value);
  return Number.isFinite(number) ? Number(number.toFixed(8)) : null;
}

function numberOrNull(value) {
  const number = Number(value);
  return Number.isFinite(number) ? number : null;
}

function formatMoney(value) {
  return typeof value === 'number' ? `$${value.toFixed(4)}` : 'pending exact usage';
}

function average(scores) {
  const values = Object.values(scores).map(Number).filter(Number.isFinite);
  return Math.round(values.reduce((sum, value) => sum + value, 0) / values.length);
}

function pairKey(firstId, secondId) {
  return [firstId, secondId].sort().join('__');
}

function getOpenRouterKey() {
  const key = process.env.OPENROUTER_API_KEY?.trim();
  if (!key) {
    throw new Error('OPENROUTER_API_KEY must be set; generateFusionRuns.js does not read local secret files.');
  }
  return key;
}

function log(message) {
  process.stderr.write(`${message}\n`);
}

main().catch((error) => {
  console.error(error.message);
  process.exit(1);
});
